### ISSUE TITLE
Error :

### ISSUE THREAD

**Issue by MoutonMesquin** [monosans/nitro-generator-checker#2]
```
┏━━━━━━━┳━━━━━━━┓
┃ Total ┃ Valid ┃
┡━━━━━━━╇━━━━━━━┩
│ 1508  │ 0     │
└───────┴───────┘
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "main.py", line 138, in main
    await NitroGeneratorChecker(
  File "main.py", line 130, in main
    await asyncio.gather(self.grab_proxies(), *coroutines)
  File "main.py", line 78, in checker
    proxy = choice(self.proxies)
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
After a while I get this error

**Comment by monosans** [comment]
Fixed in https://github.com/monosans/nitro-generator-checker/commit/b2398a511593b8faa98958f5b1981105b6b69b50.
